apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: quarkus-petclinic
spec:
  git:
    url: https://github.com/halkyonio/quarkus-tap-petclinic.git
    ref:
      branch: main
    interval: 10s