apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-petclinic-image-build
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-petclinic-image-build
  template:
    metadata:
      labels:
        app: quarkus-petclinic-image-build
    spec:
     volumes:
       - name: secret-volume-registry-creds
         secret:
           secretName: registry-creds
           defaultMode: 420
       - name: cache-dir
         persistentVolumeClaim:
           claimName: quarkus-petclinic-image-cache
       - name: layers-dir
         emptyDir: {}
       - name: home-dir
         emptyDir: {}
       - name: workspace-dir
         emptyDir: {}
       - name: platform-dir
         emptyDir: {}
       - name: report-dir
         emptyDir: {}
       - name: network-wait-launcher-dir
         emptyDir: {}
       - name: image-pull-secrets-dir
         emptyDir: {}
       - name: builder-pull-secrets-dir
         emptyDir: {}
       - name: notary-dir
         emptyDir: {}
       - name: ca-certs
         emptyDir: {}
     initContainers:
       - name: setup-ca-certs
         image: 'registry.local:5000/setup-ca-cert'
         workingDir: /workspace
         env:
           - name: CA_CERTS_DATA
             value: |
               -----BEGIN CERTIFICATE-----
               MIIGnzCCBIegAwIBAgIJAKGaHZvtLuBSMA0GCSqGSIb3DQEBCwUAMGoxCzAJBgNV
               BAYTAkJFMQ4wDAYDVQQIDAVOYW11cjESMBAGA1UEBwwJRmxvcmVubmVzMRAwDgYD
               VQQKDAdSZWQgSGF0MREwDwYDVQQLDAhTbm93ZHJvcDESMBAGA1UEAwwJbG9jYWxo
               b3N0MB4XDTIxMTAwNTE1MTEwNVoXDTIyMTAwNTE1MTEwNVowajELMAkGA1UEBhMC
               QkUxDjAMBgNVBAgMBU5hbXVyMRIwEAYDVQQHDAlGbG9yZW5uZXMxEDAOBgNVBAoM
               B1JlZCBIYXQxETAPBgNVBAsMCFNub3dkcm9wMRIwEAYDVQQDDAlsb2NhbGhvc3Qw
               ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC0G0TqS0LiLVeyTYxi0uSW
               IolKvJXNaVZmESgEvTUVWZDY4txdcTULgKX0om+oEsUXeu2ZSUEjh7Fago7aUDHf
               uKZqYaQuB5Nj9XTq3SRylo/zIf+fYolr9Tv+2gT1NRneBLi3DYQx2k+TPBGH+d3E
               atBzBN4sskSVndLawFUJQVbDInKrvmdZ8haJISYM1x9jsPF4REPx8qtiKyB1vahO
               iKtQP11mWMpQNj491TvMgruHO8SWIDjnJGwBg/a61rCN0xCuoUATHoEqPGmq7QKu
               SSRkIXn4RqhQ4O7MVq/oa3cx77W9JIfrMCKv3NxbMdF8f4xGfmCkDzn5Kt93Uqjv
               IQu8sTyui3mhr3d+KYzINTE2e7hRgXu/jyaYYpdck856Mx7O6WJsZgni/wSXVc4i
               0g/YmmFC60RTGkDfsolyEBGNby4I+PPDDRLieYw/AojyMfqQbpQFB0g/zWG2ckZ0
               XESK7Rd+bkHz0gY9vaZUUAr5yre/Pt/toEjSo4SlNs2+S25rAaN4BjATIMJNH763
               YWgHQ76SirAm3YulpxPwguoBJWeFmmM9OfgPBUPLP0rxvAozN3rXfzthrWKOMWlj
               RRNf4h1ftSvYQ6nY9Te3Oz8Zfqwk/9044fJn+rV7uIpIM3cigMmOpNsj6V62xfir
               0oZ0azKuWKgiRrOmUsNBLwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAd
               BgNVHQ4EFgQUhrw8mqrLPik6JqzThkYgaQujdvowgZwGA1UdIwSBlDCBkYAUhrw8
               mqrLPik6JqzThkYgaQujdvqhbqRsMGoxCzAJBgNVBAYTAkJFMQ4wDAYDVQQIDAVO
               YW11cjESMBAGA1UEBwwJRmxvcmVubmVzMRAwDgYDVQQKDAdSZWQgSGF0MREwDwYD
               VQQLDAhTbm93ZHJvcDESMBAGA1UEAwwJbG9jYWxob3N0ggkAoZodm+0u4FIwDgYD
               VR0PAQH/BAQDAgGGMCwGCWCGSAGG+EIBDQQfFh1PcGVuU1NMIEdlbmVyYXRlZCBD
               ZXJ0aWZpY2F0ZTAzBgNVHREELDAqgg1raW5kLXJlZ2lzdHJ5gglsb2NhbGhvc3SC
               DnJlZ2lzdHJ5LmxvY2FsMA0GCSqGSIb3DQEBCwUAA4ICAQBk5K8NW0Hzd8IwX3da
               M2LiwL+aVWjzjUONLioCesT9LC/EYPbBukRnU+e3FJtwwUoXNafMtkiYty+relku
               APv8bL0vpavmZYCsvoluhOXB4uzMII2+BCn0skWUIi6VQpcN2uO8a3H2dz2IZITD
               gNzVHU3cCunSlJNKABXeLx82IcSGSv5KTqhOmWVU9vpsfHaSXIbZIy1BU7rucSip
               5+qtHiBPD04FqyHW/IOlwsuOC+KxejgQYuteZHN5d9S4bLlWoGNzFHOMqhdrsDvF
               g93sKt7m86Cd5RS6LUt7xAQzUr7RkqkietmPTPqhPk8MuuFMLTuVapSUoSLRudAN
               xlXPoVf9RszIPgN8aGQfYU9h5OLINlZ/GP+EUpgpT/C1cJteOnJd2mjJtQcHpAfb
               ijNBC6BuVCjoO+AplnxxNNvDWhOQZTyqpxfj2RHQU/rSck3C6MxK3OT8eJ8F+vHd
               WIC8Kfa7jTvMUcTROdqv7oBMhV+XgRbObH9M6lR1AVRxb0uvCcgNg15bTWyxcm45
               Wj82KzjA8NYZ+kOmxi1b6Z0MGZPCvSDNCtaxlZMa4VtOcnr/GdZg4DoDM8kqZV80
               iq/3hLOzzff7BMgGFtWasuaTMQylZPT8OspiwfE2Jv7pAXM9weQoUZNu/lATUkYC
               cTHnhrqdgz4NCCMm605HthylFQ==
               -----END CERTIFICATE-----
         resources: {}
         volumeMounts:
           - name: ca-certs
             mountPath: /workspace
         terminationMessagePath: /dev/termination-log
         terminationMessagePolicy: File
         imagePullPolicy: IfNotPresent
       - name: prepare
         image: >-
           gcr.io/cf-build-service-public/kpack/build-init@sha256:31e95adee6d59ac46f5f2ec48208cbd154db0f4f8e6c1de1b8edf0cd9418bba8
         args:
           - '-dockerconfig=registry-creds'
         workingDir: /workspace
         env:
           - name: REGISTRY_IMAGE
             value: >-
               registry.local:5000/quarkus-petclinic-source@sha256:1d6d5a93b5a1d802a2f63dffda522fb773c555550b29003a3d278e4a1bce39c6
           - name: SOURCE_SUB_PATH
           - name: PLATFORM_ENV_VARS
             value: 'null'
           - name: IMAGE_TAG
             value: 'registry.local:5000/quarkus-petclinic'
           - name: RUN_IMAGE
             value: 'registry.local:5000/redhat-buildpacks/quarkus:run'
           - name: DNS_PROBE_HOSTNAME
             value: 'registry.local:5000'
           - name: BUILD_CHANGES
             value: >-
               [{"reason":"CONFIG","old":{"resources":{},"source":{}},"new":{"resources":{},"source":{"registry":{"image":"registry.local:5000/quarkus-petclinic-source@sha256:1d6d5a93b5a1d802a2f63dffda522fb773c555550b29003a3d278e4a1bce39c6"}}}}]
         resources: {}
         volumeMounts:
           - name: secret-volume-registry-creds
             mountPath: /var/build-secrets/registry-creds
           - name: builder-pull-secrets-dir
             readOnly: true
             mountPath: /builderPullSecrets
           - name: image-pull-secrets-dir
             readOnly: true
             mountPath: /imagePullSecrets
           - name: platform-dir
             mountPath: /platform
           - name: workspace-dir
             mountPath: /workspace
           - name: home-dir
             mountPath: /builder/home
           - name: layers-dir
             mountPath: /projectMetadata
           - name: ca-certs
             readOnly: true
             mountPath: /etc/ssl/certs
         terminationMessagePath: /dev/termination-log
         terminationMessagePolicy: File
         imagePullPolicy: IfNotPresent
       - name: detect
         image: >-
           registry.local:5000/runtime@sha256:b8559613e52b02f430fc20f553f63690fb57f5c368031bcf2c0420aae044db23
         command:
           - /cnb/lifecycle/detector
         args:
           - '-app=/workspace'
           - '-group=/layers/group.toml'
           - '-plan=/layers/plan.toml'
         env:
           - name: CNB_PLATFORM_API
             value: '0.5'
         resources: {}
         volumeMounts:
           - name: layers-dir
             mountPath: /layers
           - name: platform-dir
             mountPath: /platform
           - name: workspace-dir
             mountPath: /workspace
           - name: ca-certs
             readOnly: true
             mountPath: /etc/ssl/certs
         terminationMessagePath: /dev/termination-log
         terminationMessagePolicy: File
         imagePullPolicy: IfNotPresent
       - name: analyze
         image: >-
           registry.local:5000/runtime@sha256:b8559613e52b02f430fc20f553f63690fb57f5c368031bcf2c0420aae044db23
         command:
           - /cnb/lifecycle/analyzer
         args:
           - '-layers=/layers'
           - '-group=/layers/group.toml'
           - '-analyzed=/layers/analyzed.toml'
           - '-cache-dir=/cache'
           - 'registry.local:5000/quarkus-petclinic'
         env:
           - name: HOME
             value: /builder/home
           - name: CNB_PLATFORM_API
             value: '0.5'
         resources: {}
         volumeMounts:
           - name: layers-dir
             mountPath: /layers
           - name: workspace-dir
             mountPath: /workspace
           - name: home-dir
             mountPath: /builder/home
           - name: cache-dir
             mountPath: /cache
           - name: ca-certs
             readOnly: true
             mountPath: /etc/ssl/certs
         terminationMessagePath: /dev/termination-log
         terminationMessagePolicy: File
         imagePullPolicy: IfNotPresent
       - name: restore
         image: >-
           registry.local:5000/runtime@sha256:b8559613e52b02f430fc20f553f63690fb57f5c368031bcf2c0420aae044db23
         command:
           - /cnb/lifecycle/restorer
         args:
           - '-group=/layers/group.toml'
           - '-layers=/layers'
           - '-cache-dir=/cache'
         env:
           - name: CNB_PLATFORM_API
             value: '0.5'
         resources: {}
         volumeMounts:
           - name: layers-dir
             mountPath: /layers
           - name: cache-dir
             mountPath: /cache
           - name: ca-certs
             readOnly: true
             mountPath: /etc/ssl/certs
         terminationMessagePath: /dev/termination-log
         terminationMessagePolicy: File
         imagePullPolicy: IfNotPresent
       - name: build
         image: >-
           registry.local:5000/runtime@sha256:b8559613e52b02f430fc20f553f63690fb57f5c368031bcf2c0420aae044db23
         command:
           - /cnb/lifecycle/builder
         args:
           - '-layers=/layers'
           - '-app=/workspace'
           - '-group=/layers/group.toml'
           - '-plan=/layers/plan.toml'
         env:
           - name: CNB_PLATFORM_API
             value: '0.5'
         resources: {}
         volumeMounts:
           - name: layers-dir
             mountPath: /layers
           - name: platform-dir
             mountPath: /platform
           - name: workspace-dir
             mountPath: /workspace
           - name: ca-certs
             readOnly: true
             mountPath: /etc/ssl/certs
         terminationMessagePath: /dev/termination-log
         terminationMessagePolicy: File
         imagePullPolicy: IfNotPresent
       - name: export
         image: >-
           registry.local:5000/runtime@sha256:b8559613e52b02f430fc20f553f63690fb57f5c368031bcf2c0420aae044db23
         command:
           - /cnb/lifecycle/exporter
         args:
           - '-layers=/layers'
           - '-app=/workspace'
           - '-group=/layers/group.toml'
           - '-analyzed=/layers/analyzed.toml'
           - '-project-metadata=/layers/project-metadata.toml'
           - '-cache-dir=/cache'
           - '-report=/var/report/report.toml'
           - '-process-type=web'
           - 'registry.local:5000/quarkus-petclinic'
           - 'registry.local:5000/quarkus-petclinic:b1.20211005.161905'
         env:
           - name: HOME
             value: /builder/home
           - name: CNB_PLATFORM_API
             value: '0.5'
         resources: {}
         volumeMounts:
           - name: layers-dir
             mountPath: /layers
           - name: workspace-dir
             mountPath: /workspace
           - name: home-dir
             mountPath: /builder/home
           - name: report-dir
             mountPath: /var/report
           - name: cache-dir
             mountPath: /cache
           - name: ca-certs
             readOnly: true
             mountPath: /etc/ssl/certs
         terminationMessagePath: /dev/termination-log
         terminationMessagePolicy: File
         imagePullPolicy: IfNotPresent
     containers:
       - name: completion
         image: >-
           gcr.io/cf-build-service-public/kpack/completion@sha256:1c63b9c876b11b7bf5f83095136b690fc07860c80b62a167c41b4c3efd1910bd
         resources: {}
         volumeMounts:
           - name: ca-certs
             readOnly: true
             mountPath: /etc/ssl/certs
         terminationMessagePath: /dev/termination-log
         terminationMessagePolicy: File
         imagePullPolicy: IfNotPresent
     serviceAccountName: default
     imagePullSecrets:
      - name: registry-creds
     securityContext:
       runAsUser: 185
       runAsGroup: 185
       fsGroup: 185

