apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: quarkus-petclinic
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: quarkus-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-petclinic
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/name: quarkus-petclinic
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: dummy_repo/quarkus-petclinic:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: quarkus-petclinic
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
