apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: quarkus-petclinic
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: quarkus-petclinic
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31000
  selector:
    app.kubernetes.io/name: quarkus-petclinic
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort